/**************************************************************
 *
 *   MidiQuickFix - A Simple Midi file editor and player
 *
 *   Copyright (C) 2004-2005 John Lemcke
 *   jostle@users.sourceforge.net
 *
 *   This program is free software; you can redistribute it
 *   and/or modify it under the terms of the Artistic License
 *   as published by Larry Wall, either version 2.0,
 *   or (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *   See the Artistic License for more details.
 *
 *   You should have received a copy of the Artistic License with this Kit,
 *   in the file named "Artistic.clarified".
 *   If not, I'll be glad to provide one.
 *
 **************************************************************/

package com.lemckes.MidiQuickFix.components;

import com.lemckes.MidiQuickFix.util.DrawnIcon;
import com.lemckes.MidiQuickFix.util.Formats;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.geom.GeneralPath;
import javax.swing.event.ChangeListener;

/**
 * A slider that can have loop points
 * @version $Id$
 */
public class LoopSlider extends javax.swing.JPanel implements ChangeListener {
    
    transient private DrawnIcon inIcon;
    transient private DrawnIcon outIcon;
    transient private GeneralPath inPath = new GeneralPath();
    transient private GeneralPath outPath = new GeneralPath();
    
    private int resolution;
    
    private int loopInPoint = 0;
    private int loopOutPoint = 0;
    
    /** Creates new form LoopSlider */
    public LoopSlider() {
        initComponents();
        loopInButton.setPreferredSize(new Dimension(25,14));
        inPath.moveTo(0.3f, 0.2f);
        inPath.lineTo(0.3f, 0.8f);
        inPath.lineTo(0.7f, 0.2f);
        inPath.closePath();
        inPath.moveTo(0.1f, 0.8f);
        inPath.lineTo(0.9f, 0.8f);
        inPath.moveTo(0.2f, 0.7f);
        inPath.lineTo(0.2f, 0.8f);
        inPath.moveTo(0.4f, 0.7f);
        inPath.lineTo(0.4f, 0.8f);
        inPath.moveTo(0.6f, 0.7f);
        inPath.lineTo(0.6f, 0.8f);
        inPath.moveTo(0.8f, 0.7f);
        inPath.lineTo(0.8f, 0.8f);
        inIcon = new DrawnIcon(loopInButton, inPath);
        inIcon.setFilled(true);
        inIcon.setFillColour(Color.BLACK);
        loopInButton.setIcon(inIcon);
        
        loopOutButton.setPreferredSize(new Dimension(25,14));
        outPath.moveTo(0.3f, 0.2f);
        outPath.lineTo(0.7f, 0.2f);
        outPath.lineTo(0.7f, 0.8f);
        outPath.closePath();
        outPath.moveTo(0.1f, 0.8f);
        outPath.lineTo(0.9f, 0.8f);
        outPath.moveTo(0.2f, 0.7f);
        outPath.lineTo(0.2f, 0.8f);
        outPath.moveTo(0.4f, 0.7f);
        outPath.lineTo(0.4f, 0.8f);
        outPath.moveTo(0.6f, 0.7f);
        outPath.lineTo(0.6f, 0.8f);
        outPath.moveTo(0.8f, 0.7f);
        outPath.lineTo(0.8f, 0.8f);
        outIcon = new DrawnIcon(loopOutButton, outPath);
        outIcon.setFilled(true);
        outIcon.setFillColour(Color.BLACK);
        loopOutButton.setIcon(outIcon);
        
        durationSlider.addChangeListener(this);
    }
    
    public void addChangeListener(ChangeListener l) {
        durationSlider.addChangeListener(l);
    }
    
    public void setValue(int val) {
        durationSlider.setValue(val);
    }
    
    public void setDuration(long duration, boolean ticks, int resolution) {
        this.resolution = resolution;
        loopInPoint = 0;
        loopInField.setText(Formats.formatTicks(loopInPoint, resolution));
        loopOutPoint = (int)duration;
        loopOutField.setText(Formats.formatTicks(loopOutPoint, resolution));
        durationSlider.setDuration(duration, ticks, resolution);
    }
    
    public void stateChanged(javax.swing.event.ChangeEvent changeEvent) {
        int val = durationSlider.getValue();
        currPositionField.setText(Formats.formatTicks(val, resolution));
    }

    public int getLoopInPoint() {
        return loopInPoint;
    }

    public void setLoopInPoint(int loopInPoint) {
        this.loopInPoint = loopInPoint;
    }

    public int getLoopOutPoint() {
        return loopOutPoint;
    }

    public void setLoopOutPoint(int loopOutPoint) {
        this.loopOutPoint = loopOutPoint;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loopInField = new javax.swing.JTextField();
        loopOutField = new javax.swing.JTextField();
        durationSlider = new com.lemckes.MidiQuickFix.components.DurationSlider();
        currPositionField = new javax.swing.JTextField();
        loopInButton = new javax.swing.JButton();
        loopInLabel = new javax.swing.JLabel();
        loopOutButton = new javax.swing.JButton();
        loopOutLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(3, 3, 3, 3)));
        loopInField.setColumns(8);
        loopInField.setFont(new java.awt.Font("DialogInput", 0, 14));
        loopInField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
        add(loopInField, gridBagConstraints);

        loopOutField.setColumns(8);
        loopOutField.setFont(new java.awt.Font("DialogInput", 0, 14));
        loopOutField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(1, 0, 0, 0);
        add(loopOutField, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        add(durationSlider, gridBagConstraints);

        currPositionField.setColumns(8);
        currPositionField.setFont(new java.awt.Font("DialogInput", 0, 14));
        currPositionField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(1, 3, 0, 2);
        add(currPositionField, gridBagConstraints);

        loopInButton.setToolTipText("Set Loop-In Point");
        loopInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loopInButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(loopInButton, gridBagConstraints);

        loopInLabel.setFont(new java.awt.Font("Dialog", 1, 14));
        loopInLabel.setText(" In ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        add(loopInLabel, gridBagConstraints);

        loopOutButton.setToolTipText("Set Loop-Out Point");
        loopOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loopOutButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        add(loopOutButton, gridBagConstraints);

        loopOutLabel.setFont(new java.awt.Font("Dialog", 1, 14));
        loopOutLabel.setText("Out");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 1, 0, 0);
        add(loopOutLabel, gridBagConstraints);

    }
    // </editor-fold>//GEN-END:initComponents
    
    private void loopOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loopOutButtonActionPerformed
        loopOutPoint = durationSlider.getValue();
        loopOutField.setText(Formats.formatTicks(loopOutPoint, resolution));
    }//GEN-LAST:event_loopOutButtonActionPerformed
    
    private void loopInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loopInButtonActionPerformed
        loopInPoint = durationSlider.getValue();
        loopInField.setText(Formats.formatTicks(loopInPoint, resolution));
    }//GEN-LAST:event_loopInButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField currPositionField;
    private com.lemckes.MidiQuickFix.components.DurationSlider durationSlider;
    private javax.swing.JButton loopInButton;
    private javax.swing.JTextField loopInField;
    private javax.swing.JLabel loopInLabel;
    private javax.swing.JButton loopOutButton;
    private javax.swing.JTextField loopOutField;
    private javax.swing.JLabel loopOutLabel;
    // End of variables declaration//GEN-END:variables
    
}
