/*
 * TransposeDialog.java
 *
 * Created on 19 June 2007, 23:30
 */

package com.lemckes.MidiQuickFix;

import com.lemckes.MidiQuickFix.util.UiStrings;
import javax.swing.DefaultComboBoxModel;

/**
 * Allow the user to create a Midi event.
 *
 * @version $Id$
 */
public class CreateEventDialog extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    
    /** Creates new form TransposeDialog */
    public CreateEventDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Object[] s = InstrumentNames.getNameArray();
        patchCombo.setModel(new DefaultComboBoxModel(s));
        s = NoteNames.getNoteNameArray();
        noteCombo.setModel(new DefaultComboBoxModel(s));
        s = Controllers.getNameArray();
        controllerCombo.setModel(new DefaultComboBoxModel(s));
        s = MetaEvent.getNameArray();
        metaEventCombo.setModel(new DefaultComboBoxModel(s));
        pack();
    }
    
    /**
     * Get the status of the dialog when it was closed
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        eventTypeGroup = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        tickPanel = new javax.swing.JPanel();
        positionLabel = new javax.swing.JLabel();
        positionField = new javax.swing.JFormattedTextField();
        shortEventPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        channelLabel = new javax.swing.JLabel();
        channelField = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        noteOnRadio = new javax.swing.JRadioButton();
        noteOffRadio = new javax.swing.JRadioButton();
        polyRadio = new javax.swing.JRadioButton();
        noteCombo = new javax.swing.JComboBox();
        noteData2Label = new javax.swing.JLabel();
        noteData2Field = new javax.swing.JFormattedTextField();
        patchRadio = new javax.swing.JRadioButton();
        patchCombo = new javax.swing.JComboBox();
        controlRadio = new javax.swing.JRadioButton();
        controllerCombo = new javax.swing.JComboBox();
        data2Label2 = new javax.swing.JLabel();
        data2Field2 = new javax.swing.JFormattedTextField();
        bendRadio = new javax.swing.JRadioButton();
        data1Field3 = new javax.swing.JFormattedTextField();
        channelPressureRadio = new javax.swing.JRadioButton();
        data1Field4 = new javax.swing.JFormattedTextField();
        metaEventPanel = new javax.swing.JPanel();
        metaEventRadio = new javax.swing.JRadioButton();
        metaEventCombo = new javax.swing.JComboBox();
        metaDataLabel = new javax.swing.JLabel();
        metaDataField = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        insertButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setTitle(UiStrings.getString("create_event")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.PAGE_AXIS));

        mainPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tickPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        positionLabel.setText(UiStrings.getString("event_position")); // NOI18N
        tickPanel.add(positionLabel);

        positionField.setColumns(8);
        positionField.setText("00000:000");
        tickPanel.add(positionField);

        mainPanel.add(tickPanel);

        shortEventPanel.setLayout(new javax.swing.BoxLayout(shortEventPanel, javax.swing.BoxLayout.PAGE_AXIS));

        shortEventPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(UiStrings.getString("short_event"))); // NOI18N
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        channelLabel.setText(UiStrings.getString("channel")); // NOI18N
        jPanel2.add(channelLabel);

        channelField.setColumns(3);
        jPanel2.add(channelField);

        shortEventPanel.add(jPanel2);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        eventTypeGroup.add(noteOnRadio);
        noteOnRadio.setText(UiStrings.getString("poly_pressure")); // NOI18N
        noteOnRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        noteOnRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 9, 0);
        jPanel1.add(noteOnRadio, gridBagConstraints);

        eventTypeGroup.add(noteOffRadio);
        noteOffRadio.setText(UiStrings.getString("note_on")); // NOI18N
        noteOffRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        noteOffRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(noteOffRadio, gridBagConstraints);

        eventTypeGroup.add(polyRadio);
        polyRadio.setText(UiStrings.getString("note_on")); // NOI18N
        polyRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        polyRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel1.add(polyRadio, gridBagConstraints);

        noteCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 9, 0);
        jPanel1.add(noteCombo, gridBagConstraints);

        noteData2Label.setText(UiStrings.getString("data2")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 9, 0);
        jPanel1.add(noteData2Label, gridBagConstraints);

        noteData2Field.setColumns(3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 9, 0);
        jPanel1.add(noteData2Field, gridBagConstraints);

        eventTypeGroup.add(patchRadio);
        patchRadio.setText(UiStrings.getString("patch")); // NOI18N
        patchRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        patchRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 9, 0);
        jPanel1.add(patchRadio, gridBagConstraints);

        patchCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 9, 0);
        jPanel1.add(patchCombo, gridBagConstraints);

        eventTypeGroup.add(controlRadio);
        controlRadio.setText(UiStrings.getString("control_change")); // NOI18N
        controlRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        controlRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 9, 0);
        jPanel1.add(controlRadio, gridBagConstraints);

        controllerCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 9, 0);
        jPanel1.add(controllerCombo, gridBagConstraints);

        data2Label2.setText(UiStrings.getString("data2")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 9, 0);
        jPanel1.add(data2Label2, gridBagConstraints);

        data2Field2.setColumns(3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 9, 0);
        jPanel1.add(data2Field2, gridBagConstraints);

        eventTypeGroup.add(bendRadio);
        bendRadio.setText(UiStrings.getString("pitch_bend")); // NOI18N
        bendRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        bendRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 9, 0);
        jPanel1.add(bendRadio, gridBagConstraints);

        data1Field3.setColumns(5);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 9, 0);
        jPanel1.add(data1Field3, gridBagConstraints);

        eventTypeGroup.add(channelPressureRadio);
        channelPressureRadio.setText(UiStrings.getString("channel_pressure")); // NOI18N
        channelPressureRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        channelPressureRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 9, 0);
        jPanel1.add(channelPressureRadio, gridBagConstraints);

        data1Field4.setColumns(3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 9, 0);
        jPanel1.add(data1Field4, gridBagConstraints);

        shortEventPanel.add(jPanel1);

        mainPanel.add(shortEventPanel);

        metaEventPanel.setLayout(new java.awt.GridBagLayout());

        metaEventPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(UiStrings.getString("meta_event"))); // NOI18N
        eventTypeGroup.add(metaEventRadio);
        metaEventRadio.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        metaEventRadio.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        metaEventPanel.add(metaEventRadio, gridBagConstraints);

        metaEventCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        metaEventPanel.add(metaEventCombo, gridBagConstraints);

        metaDataLabel.setText(UiStrings.getString("data")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
        metaEventPanel.add(metaDataLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        metaEventPanel.add(metaDataField, gridBagConstraints);

        mainPanel.add(metaEventPanel);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        buttonPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        insertButton.setText(UiStrings.getString("insert")); // NOI18N
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(insertButton);

        closeButton.setText(UiStrings.getString("close")); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(closeButton);

        jPanel3.add(buttonPanel);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_insertButtonActionPerformed
    
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeButtonActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                javax.swing.JFrame f = new javax.swing.JFrame();
                f.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
                new CreateEventDialog(f, true).setVisible(true);
                System.exit(0);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bendRadio;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JFormattedTextField channelField;
    private javax.swing.JLabel channelLabel;
    private javax.swing.JRadioButton channelPressureRadio;
    private javax.swing.JButton closeButton;
    private javax.swing.JRadioButton controlRadio;
    private javax.swing.JComboBox controllerCombo;
    private javax.swing.JFormattedTextField data1Field3;
    private javax.swing.JFormattedTextField data1Field4;
    private javax.swing.JFormattedTextField data2Field2;
    private javax.swing.JLabel data2Label2;
    private javax.swing.ButtonGroup eventTypeGroup;
    private javax.swing.JButton insertButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JFormattedTextField metaDataField;
    private javax.swing.JLabel metaDataLabel;
    private javax.swing.JComboBox metaEventCombo;
    private javax.swing.JPanel metaEventPanel;
    private javax.swing.JRadioButton metaEventRadio;
    private javax.swing.JComboBox noteCombo;
    private javax.swing.JFormattedTextField noteData2Field;
    private javax.swing.JLabel noteData2Label;
    private javax.swing.JRadioButton noteOffRadio;
    private javax.swing.JRadioButton noteOnRadio;
    private javax.swing.JComboBox patchCombo;
    private javax.swing.JRadioButton patchRadio;
    private javax.swing.JRadioButton polyRadio;
    private javax.swing.JFormattedTextField positionField;
    private javax.swing.JLabel positionLabel;
    private javax.swing.JPanel shortEventPanel;
    private javax.swing.JPanel tickPanel;
    // End of variables declaration//GEN-END:variables
    
    private int returnStatus = RET_CANCEL;
    
}
