/**************************************************************
 *
 *   MidiQuickFix - A Simple Midi file editor and player
 *
 *   Copyright (C) 2004-2010 John Lemcke
 *   jostle@users.sourceforge.net
 *
 *   This program is free software; you can redistribute it
 *   and/or modify it under the terms of the Artistic License
 *   as published by Larry Wall, either version 2.0,
 *   or (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *   See the Artistic License for more details.
 *
 *   You should have received a copy of the Artistic License with this Kit,
 *   in the file named "Artistic.clarified".
 *   If not, I'll be glad to provide one.
 *
 **************************************************************/
package com.lemckes.MidiQuickFix;

import com.lemckes.MidiQuickFix.util.MqfSequence;
import com.lemckes.MidiQuickFix.util.UiStrings;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.util.Map.Entry;
import javax.swing.JLabel;

/**
 * Allow the user to create a new track
 */
public class SongInfoDialog extends javax.swing.JDialog
{

    /**
     * Create a new CreateTrackDialog for the given Sequence
     * @param seq the sequence in which to create the track
     * @param parent
     * @param modal
     */
    public SongInfoDialog(
        MqfSequence seq, java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        if (seq != null) {
            JLabel tempLabel = new javax.swing.JLabel();
            Font keyFont = tempLabel.getFont().deriveFont(
                tempLabel.getFont().getStyle() | java.awt.Font.BOLD);
            Font valueFont = tempLabel.getFont().deriveFont(
                tempLabel.getFont().getStyle() & ~java.awt.Font.BOLD);

            GridBagConstraints keyGBC = new GridBagConstraints();
            keyGBC.gridx = 0;
            keyGBC.gridy = 0;
            keyGBC.anchor = java.awt.GridBagConstraints.EAST;
            keyGBC.insets = new java.awt.Insets(0, 0, 0, 3);

            GridBagConstraints separatorGBC = new GridBagConstraints();
            separatorGBC = new java.awt.GridBagConstraints();
            separatorGBC.gridx = 1;
            separatorGBC.gridy = 0;
            separatorGBC.insets = new java.awt.Insets(0, 3, 0, 3);

            GridBagConstraints valueGBC = new java.awt.GridBagConstraints();
            valueGBC.gridx = 2;
            valueGBC.gridy = 0;
            valueGBC.anchor = java.awt.GridBagConstraints.WEST;
            valueGBC.insets = new java.awt.Insets(0, 3, 0, 0);

            if (seq.getSongInfo().isEmpty())
            {
                JLabel keyLabel = new javax.swing.JLabel(
                    UiStrings.getString("SongInfoDialog.noInfoMessage"));
                mainPanel.add(keyLabel, keyGBC);
            }
            for (Entry<String, String> e : seq.getSongInfo().entrySet()) {
                JLabel keyLabel = new javax.swing.JLabel(e.getKey());
                JLabel separatorLabel = new javax.swing.JLabel(":");
                JLabel valueLabel = new javax.swing.JLabel(e.getValue());
                keyLabel.setFont(keyFont);
                separatorLabel.setFont(keyFont);
                valueLabel.setFont(valueFont);
                mainPanel.add(keyLabel, keyGBC);
                mainPanel.add(separatorLabel, separatorGBC);
                mainPanel.add(valueLabel, valueGBC);
                ++keyGBC.gridy;
                ++separatorGBC.gridy;
                ++valueGBC.gridy;
            }

            setLocationRelativeTo(parent);
            pack();
        }
    }

    private void doClose() {
        setVisible(false);
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/lemckes/MidiQuickFix/Bundle"); // NOI18N
        setTitle(bundle.getString("SongInfoDialog.title")); // NOI18N
        setName("Form"); // NOI18N

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("SongInfoDialog.title"))); // NOI18N
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.GridBagLayout());
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        buttonPanel.setName("buttonPanel"); // NOI18N
        buttonPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        cancelButton.setText(bundle.getString("SongInfoDialog.cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        jPanel2.add(buttonPanel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
