/**************************************************************
 *
 *   MidiQuickFix - A Simple Midi file editor and player
 *
 *   Copyright (C) 2004-2005 John Lemcke
 *   jostle@users.sourceforge.net
 *
 *   This program is free software; you can redistribute it
 *   and/or modify it under the terms of the Artistic License
 *   as published by Larry Wall, either version 2.0,
 *   or (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *   See the Artistic License for more details.
 *
 *   You should have received a copy of the Artistic License with this Kit,
 *   in the file named "Artistic.clarified".
 *   If not, I'll be glad to provide one.
 *
 **************************************************************/
package com.lemckes.MidiQuickFix;

import com.lemckes.MidiQuickFix.util.TableColumnWidthSetter;

/**
 * A table that displays summary info about each track in a sequence.
 * @version $Id$
 */
public class TrackSummaryTable extends javax.swing.JTable {
    static final long serialVersionUID = 4128873234789727596L;

    /** Creates new form BeanForm */
    public TrackSummaryTable() {
        initComponents();
        Object[] widths =
            {"99", "Cor Anglais or longer", "00000:000", "00000:000", "16", // NOI18N
             true, true};
        TableColumnWidthSetter.setColumnWidths(this, widths);
    }

    /**
     * Set the sequence that is to be displayed
     * @param seq the sequence that is to be displayed
     */
    public void setSequence(javax.sound.midi.Sequence seq) {
        setModel(new TrackSummaryTableModel(seq));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

    }
    // </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
