/**************************************************************
 *
 *   MidiQuickFix - A Simple Midi file editor and player
 *
 *   Copyright (C) 2004-2010 John Lemcke
 *   jostle@users.sourceforge.net
 *
 *   This program is free software; you can redistribute it
 *   and/or modify it under the terms of the Artistic License
 *   as published by Larry Wall, either version 2.0,
 *   or (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *   See the Artistic License for more details.
 *
 *   You should have received a copy of the Artistic License with this Kit,
 *   in the file named "Artistic.clarified".
 *   If not, I'll be glad to provide one.
 *
 **************************************************************/
package com.lemckes.MidiQuickFix;

import com.lemckes.MidiQuickFix.util.UiStrings;
import java.awt.Component;

/**
 * Allow the user to create a new track
 */
public class TrackUpdateUtilDialog extends javax.swing.JDialog
{

    TrackEditorPanel mEditor;

    /**
     * Create a new CreateTrackDialog for the given Sequence
     * @param editor
     * @param parent
     * @param modal
     */
    public TrackUpdateUtilDialog(
        TrackEditorPanel editor, Component parent, boolean modal) {
        super(MidiQuickFix.getMainFrame(), modal);
        initComponents();
        mEditor = editor;
        setLocationRelativeTo(parent);
        pack();
    }

    private void doClose() {
        setVisible(false);
        dispose();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainPanel = new javax.swing.JPanel();
        convertNoteOnLabel = new javax.swing.JLabel();
        convertNoteOnButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        convertTextLabel = new javax.swing.JLabel();
        convertTextButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        deleteNotesLabel = new javax.swing.JLabel();
        removeNotesButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        convertTypeZeroLabel = new javax.swing.JLabel();
        convertTypeZeroButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("com/lemckes/MidiQuickFix/Bundle"); // NOI18N
        setTitle(bundle.getString("TrackUpdateUtilDialog.title")); // NOI18N
        setName("Form"); // NOI18N

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("TrackUpdateUtilDialog.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("DejaVu Sans", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new java.awt.GridBagLayout());

        convertNoteOnLabel.setText(UiStrings.getString("TrackUpdateUtilDialog.convertNoteOnLabel.text")); // NOI18N
        convertNoteOnLabel.setName("convertNoteOnLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 6);
        mainPanel.add(convertNoteOnLabel, gridBagConstraints);

        convertNoteOnButton.setText(UiStrings.getString("TrackUpdateUtilDialog.convertNoteOnButton.text")); // NOI18N
        convertNoteOnButton.setName("convertNoteOnButton"); // NOI18N
        convertNoteOnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertNoteOnButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        mainPanel.add(convertNoteOnButton, gridBagConstraints);

        jSeparator1.setName("jSeparator1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        mainPanel.add(jSeparator1, gridBagConstraints);

        convertTextLabel.setText(UiStrings.getString("TrackUpdateUtilDialog.convertTextLabel.text")); // NOI18N
        convertTextLabel.setName("convertTextLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 6);
        mainPanel.add(convertTextLabel, gridBagConstraints);

        convertTextButton.setText(UiStrings.getString("TrackUpdateUtilDialog.convertTextButton.text")); // NOI18N
        convertTextButton.setName("convertTextButton"); // NOI18N
        convertTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertTextButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        mainPanel.add(convertTextButton, gridBagConstraints);

        jSeparator2.setName("jSeparator2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        mainPanel.add(jSeparator2, gridBagConstraints);

        deleteNotesLabel.setText(UiStrings.getString("TrackUpdateUtilDialog.deleteNotesLabel.text")); // NOI18N
        deleteNotesLabel.setName("deleteNotesLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 6);
        mainPanel.add(deleteNotesLabel, gridBagConstraints);

        removeNotesButton.setText(UiStrings.getString("TrackUpdateUtilDialog.removeNotesButton.text")); // NOI18N
        removeNotesButton.setName("removeNotesButton"); // NOI18N
        removeNotesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeNotesButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        mainPanel.add(removeNotesButton, gridBagConstraints);

        jSeparator3.setName("jSeparator3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 7, 0);
        mainPanel.add(jSeparator3, gridBagConstraints);

        convertTypeZeroLabel.setText(UiStrings.getString("TrackUpdateUtilDialog.convertTypeZeroLabel.text")); // NOI18N
        convertTypeZeroLabel.setName("convertTypeZeroLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 6);
        mainPanel.add(convertTypeZeroLabel, gridBagConstraints);

        convertTypeZeroButton.setText(UiStrings.getString("TrackUpdateUtilDialog.convertTypeZeroButton.text")); // NOI18N
        convertTypeZeroButton.setName("convertTypeZeroButton"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        mainPanel.add(convertTypeZeroButton, gridBagConstraints);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        buttonPanel.setName("buttonPanel"); // NOI18N
        buttonPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        cancelButton.setText(bundle.getString("TrackUpdateUtilDialog.cancelButton.text")); // NOI18N
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        jPanel2.add(buttonPanel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void convertNoteOnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertNoteOnButtonActionPerformed
        mEditor.convertNoteOn();
}//GEN-LAST:event_convertNoteOnButtonActionPerformed

    private void convertTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertTextButtonActionPerformed
        mEditor.convertText();
}//GEN-LAST:event_convertTextButtonActionPerformed

    private void removeNotesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeNotesButtonActionPerformed
        mEditor.removeNotes();
}//GEN-LAST:event_removeNotesButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton convertNoteOnButton;
    private javax.swing.JLabel convertNoteOnLabel;
    private javax.swing.JButton convertTextButton;
    private javax.swing.JLabel convertTextLabel;
    private javax.swing.JButton convertTypeZeroButton;
    private javax.swing.JLabel convertTypeZeroLabel;
    private javax.swing.JLabel deleteNotesLabel;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton removeNotesButton;
    // End of variables declaration//GEN-END:variables
}
